(()=>{'use strict';const W=window.WS=window.WS||{};W.clamp=(v,a,b)=>Math.max(a,Math.min(b,v));W.lerp=(a,b,t)=>a+(b-a)*t;W.dist=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y);W.wrapDeg=d=>((d+180)%360+360)%360-180;W.deviceOri=null;W.lastOri=null;W.trackerQuality=0;W.trackerLabel='—';
class WallTracker{constructor(video,canvas){this.video=video;this.out=canvas;this.tw=320;this.th=240;this.c=document.createElement('canvas');this.g=null;this.gray=null;this.features=[];this.anchor={x:160,y:120};this.active=false;this.frame=0;this.angle=0;this.scale=1;this.lastVideoTime=-1;this.avoid=[]}
resize(w,h){this.th=Math.max(180,Math.round(this.tw*h/w));this.c.width=this.tw;this.c.height=this.th;this.g=this.c.getContext('2d',{willReadFrequently:true});this.gray=new Uint8Array(this.tw*this.th)}
grab(){this.g.drawImage(this.video,0,0,this.tw,this.th);const d=this.g.getImageData(0,0,this.tw,this.th).data;for(let i=0,j=0;i<d.length;i+=4,j++)this.gray[j]=(d[i]*77+d[i+1]*150+d[i+2]*29)>>8}
variance(x,y,r=4){let s=0,s2=0,n=0;for(let yy=-r;yy<=r;yy++)for(let xx=-r;xx<=r;xx++){const v=this.gray[(y+yy)*this.tw+x+xx];s+=v;s2+=v*v;n++}return s2/n-(s/n)*(s/n)}
patch(x,y,r=3){const vals=new Float32Array((r*2+1)**2);let s=0,k=0;for(let yy=-r;yy<=r;yy++)for(let xx=-r;xx<=r;xx++){const v=this.gray[(y+yy)*this.tw+x+xx];vals[k++]=v;s+=v}const mean=s/vals.length;let norm=0;for(let i=0;i<vals.length;i++){vals[i]-=mean;norm+=vals[i]*vals[i]}return{vals,norm:Math.sqrt(norm)+1e-6,r}}
seed(x,y,avoid=[]){this.grab();this.lastVideoTime=this.video.currentTime;this.anchor={x:x/this.out.width*this.tw,y:y/this.out.height*this.th};this.avoid=avoid.map(p=>({x:p.x/this.out.width*this.tw,y:p.y/this.out.height*this.th}));this.features=[];this.refill();this.active=this.features.length>=4;this.frame=0;this.angle=0;this.scale=1;W.trackerQuality=this.active?.9:.15;W.trackerLabel=this.active?'AGGANCIO':'POCO DETTAGLIO';W.lastOri=W.deviceOri?{...W.deviceOri}:null}
refill(){const cand=[];for(let gy=-5;gy<=5;gy++)for(let gx=-6;gx<=6;gx++){const x=Math.round(this.anchor.x+gx*12),y=Math.round(this.anchor.y+gy*12);if(x<12||y<12||x>=this.tw-12||y>=this.th-12)continue;if(this.avoid.some(p=>Math.hypot(p.x-x,p.y-y)<18))continue;const score=this.variance(x,y,4);if(score>70)cand.push({x,y,score})}cand.sort((a,b)=>b.score-a.score);for(const c of cand){if(this.features.length>=16)break;if(this.features.every(f=>Math.hypot(f.x-c.x,f.y-c.y)>14))this.features.push({x:c.x,y:c.y,patch:this.patch(c.x,c.y,3)})}}
corr(p,x,y){const r=p.r,n=(r*2+1)**2;let s=0,s2=0,k=0;for(let yy=-r;yy<=r;yy++)for(let xx=-r;xx<=r;xx++){const v=this.gray[(y+yy)*this.tw+x+xx];s+=v;s2+=v*v}const mean=s/n,norm=Math.sqrt(Math.max(1e-6,s2-n*mean*mean));let dot=0;for(let yy=-r;yy<=r;yy++)for(let xx=-r;xx<=r;xx++)dot+=p.vals[k++]*(this.gray[(y+yy)*this.tw+x+xx]-mean);return dot/(p.norm*norm+1e-6)}
match(f){let best={c:-2,x:f.x,y:f.y},second=-2;const R=13;for(let yy=-R;yy<=R;yy+=2)for(let xx=-R;xx<=R;xx+=2){const x=Math.round(f.x+xx),y=Math.round(f.y+yy);if(x<5||y<5||x>=this.tw-5||y>=this.th-5)continue;const c=this.corr(f.patch,x,y);if(c>best.c){second=best.c;best={c,x,y}}else if(c>second)second=c}for(let y=best.y-2;y<=best.y+2;y++)for(let x=best.x-2;x<=best.x+2;x++){if(x<5||y<5||x>=this.tw-5||y>=this.th-5)continue;const c=this.corr(f.patch,x,y);if(c>best.c)best={c,x,y}}best.u=best.c-second;return best}
similarity(ms){let sw=0,px=0,py=0,qx=0,qy=0;for(const m of ms){sw+=m.w;px+=m.w*m.px;py+=m.w*m.py;qx+=m.w*m.qx;qy+=m.w*m.qy}if(sw<1e-5)return null;px/=sw;py/=sw;qx/=sw;qy/=sw;let den=0,a=0,b=0;for(const m of ms){const x=m.px-px,y=m.py-py,u=m.qx-qx,v=m.qy-qy;den+=m.w*(x*x+y*y);a+=m.w*(x*u+y*v);b+=m.w*(x*v-y*u)}if(den<1)return null;a/=den;b/=den;return{a,b,tx:qx-a*px+b*py,ty:qy-b*px-a*py}}
tp(p,t){return{x:t.a*p.x-t.b*p.y+t.tx,y:t.b*p.x+t.a*p.y+t.ty}}
update(){if(!this.active||this.video.readyState<2||this.video.currentTime===this.lastVideoTime)return null;this.lastVideoTime=this.video.currentTime;this.grab();let ms=[];for(const f of this.features){const m=this.match(f);if(m.c>.54&&m.u>.015)ms.push({f,px:f.x,py:f.y,qx:m.x,qy:m.y,w:W.clamp((m.c-.45)*2.2,.05,1),score:m.c})}if(ms.length>=4){let t=this.similarity(ms);if(t){const rr=ms.map(m=>{const q=this.tp(m,t);return Math.hypot(q.x-m.qx,q.y-m.qy)}).sort((a,b)=>a-b),med=rr[Math.floor(rr.length/2)]||2;ms=ms.filter(m=>{const q=this.tp(m,t);return Math.hypot(q.x-m.qx,q.y-m.qy)<Math.max(2.8,med*2.6)});if(ms.length>=4)t=this.similarity(ms)}if(t&&ms.length>=4){this.anchor=this.tp(this.anchor,t);this.scale*=Math.hypot(t.a,t.b);this.angle+=Math.atan2(t.b,t.a);for(const m of ms){m.f.x=m.qx;m.f.y=m.qy;m.f.patch=this.patch(Math.round(m.qx),Math.round(m.qy),3)}this.features=this.features.filter(f=>ms.some(m=>m.f===f));this.frame++;if(this.features.length<9||this.frame%45===0)this.refill();const mean=ms.reduce((z,m)=>z+m.score,0)/ms.length;W.trackerQuality=W.lerp(W.trackerQuality,W.clamp((ms.length/10)*mean,0,1),.28);W.trackerLabel=W.trackerQuality>.7?'FERMO':W.trackerQuality>.42?'SEGUITO':'DEBOLE';W.lastOri=W.deviceOri?{...W.deviceOri}:W.lastOri;const sx=this.out.width/this.tw,sy=this.out.height/this.th;return{a:t.a,b:t.b,tx:t.tx*sx,ty:t.ty*sy}}}
if(W.deviceOri&&W.lastOri){const da=W.wrapDeg(W.deviceOri.alpha-W.lastOri.alpha),db=W.deviceOri.beta-W.lastOri.beta;if(Math.abs(da)<8&&Math.abs(db)<8){const dx=W.clamp(-da*this.tw/62,-10,10),dy=W.clamp(db*this.th/48,-10,10);this.anchor.x+=dx;this.anchor.y+=dy;W.lastOri={...W.deviceOri};W.trackerQuality*=.94;W.trackerLabel='SENSOR';return{a:1,b:0,tx:dx*this.out.width/this.tw,ty:dy*this.out.height/this.th}}}W.trackerQuality*=.90;W.trackerLabel='PERSO';return null}
canvasAnchor(){return{x:this.anchor.x/this.tw*this.out.width,y:this.anchor.y/this.th*this.out.height}}
}
W.WallTracker=WallTracker;window.addEventListener('deviceorientation',e=>{if(Number.isFinite(e.alpha)&&Number.isFinite(e.beta))W.deviceOri={alpha:e.alpha,beta:e.beta,gamma:e.gamma||0}})})();